In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('pew.txt')

In [14]:
df.head()

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don’t know/refused,15,14,15,11,10,35,21,17,18,116

In [15]:
pew_long = pd.melt(df, id_vars='religion')

In [16]:
pew_long = pd.melt(df, id_vars='religion',var_name='income',value_name='count')
pew_long.head()

             religion income  count
0            Agnostic  <$10k     27
1             Atheist  <$10k     12
2            Buddhist  <$10k     27
3            Catholic  <$10k    418
4  Don’t know/refused  <$10k     15

### pandas data type
#### numereic: int64, float64, bull
#### string: object, category(statistics)
#### time, date

In [39]:
ebola = pd.read_csv(
    'E:/Workspace/Bigdata_Edu/1. Lecture Note/16. pandas_180725~27/data_4/country_timeseries.csv')

In [40]:
ebola.head()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

In [46]:
ebola_long = pd.melt(ebola,id_vars=['Date','Day'])

In [47]:
ebola_long.head()

         Date  Day      variable   value
0    1/5/2015  289  Cases_Guinea  2776.0
1    1/4/2015  288  Cases_Guinea  2775.0
2    1/3/2015  287  Cases_Guinea  2769.0
3    1/2/2015  286  Cases_Guinea     NaN
4  12/31/2014  284  Cases_Guinea  2730.0

In [49]:
##split
'Cases_Guinea'.split('_')

['Cases', 'Guinea']

In [50]:
var_split = ebola_long['variable'].str.split('_')

In [51]:
type(var_split)

pandas.core.series.Series

In [53]:
var_split.head()

0    [Cases, Guinea]
1    [Cases, Guinea]
2    [Cases, Guinea]
3    [Cases, Guinea]
4    [Cases, Guinea]
Name: variable, dtype: object

In [54]:
status_value = var_split[0]

In [80]:
weather = pd.read_csv(
    'E:/Workspace/Bigdata_Edu/1. Lecture Note/16. pandas_180725~27/data_1/weather.txt',sep='\t')

In [88]:
weather.shape

(22, 35)

In [90]:
del weather['id']

In [91]:
weather_long = pd.melt(weather,id_vars=['year','month','element'])

In [99]:
wt_group = weather_long.groupby(['year','month','element','variable']).mean()
wt_group.head()

                             value
year month element variable
2010 1     TMAX    d1          NaN
                   d10         NaN
                   d11         NaN
                   d12         NaN
                   d13         NaN

In [100]:
bb = pd.read_csv('E:/Workspace/Bigdata_Edu/1. Lecture Note/16. pandas_180725~27/data_1/billboard.csv')

In [101]:
bb.head()

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
bb_long = pd.melt(bb,
                  id_vars=['year','artist.inverted','track','time','genre','date.entered','date.peaked'],
                  var_name='week',
                  value_name='rating')

In [111]:
bb_long.pivot_table(columns=['genre','artist.inverted','track'],
                    index=['year','week'],
                    values='rating')

genre                                        2000-08-19       Country  \
artist.inverted 98?,Give Me Just One Night (Una Noche)" Adkins, Trace
track                                              3:24          More
year week
2000 x10th.week                                     7.0          83.0
     x11th.week                                    22.0          92.0
     x12th.week                                    29.0           NaN
     x13th.week                                    36.0           NaN
     x14th.week                                    47.0           NaN
     x15th.week                                    67.0           NaN
     x16th.week                                    66.0           NaN
     x17th.week                                    84.0           NaN
     x18th.week                                    93.0           NaN
     x19th.week                                    94.0           NaN
     x1st.week                                     39.0          84.0
     x20th.week                                     NaN           NaN
     x21st.week                                     NaN           NaN
     x22nd.week                                     NaN           NaN
     x23rd.week                                     NaN           NaN
     x24th.week                                     NaN           NaN
     x25th.week                                     NaN           NaN
     x26th.week                                     NaN           NaN
     x27th.week                                     NaN           NaN
     x28th.week                                     NaN           NaN
     x29th.week                                     NaN           NaN
     x2nd.week                                     34.0          84.0
     x30th.week                                     NaN           NaN
     x31st.week                                     NaN           NaN
     x32nd.week                                     NaN           NaN
     x33rd.week                                     NaN           NaN
     x34th.week                                     NaN           NaN
     x35th.week                                     NaN           NaN
     x36th.week                                     NaN           NaN
     x37th.week                                     NaN           NaN
...                                                 ...           ...
     x52nd.week                                     NaN           NaN
     x53rd.week                                     NaN           NaN
     x54th.week                                     NaN           NaN
     x55th.week                                     NaN           NaN
     x56th.week                                     NaN           NaN
     x57th.week                                     NaN           NaN
     x58th.week                                     NaN           NaN
     x59th.week                                     NaN           NaN
     x5th.week                                     19.0          73.0
     x60th.week                                     NaN           NaN
     x61st.week                                     NaN           NaN
     x62nd.week                                     NaN           NaN
     x63rd.week                                     NaN           NaN
     x64th.week                                     NaN           NaN
     x65th.week                                     NaN           NaN
     x66th.week                                     NaN           NaN
     x67th.week                                     NaN           NaN
     x68th.week                                     NaN           NaN
     x69th.week                                     NaN           NaN
     x6th.week                                      2.0          69.0
     x70th.week                                     NaN           NaN
     x71st.week                                     NaN           NaN
     x72nd.week                                     NaN           NaN
     x73rd.week                                     NaN           NaN
     x74th.week                                     NaN           NaN
     x75th.week                                     NaN           NaN
     x76th.week                                     NaN           NaN
     x7th.week                                      2.0          68.0
     x8th.week                                      3.0          65.0
     x9th.week                                      6.0          73.0

genre                                                 \
artist.inverted             Allan, Gary Black, Clint
track           Smoke Rings In The Dark   Been There
year week
2000 x10th.week                     NaN         44.0
     x11th.week                     NaN         44.0
     x12th.week                     NaN         55.0
     x13th.week                     NaN         53.0
     x14th.week                     NaN         53.0
     x15th.week                     NaN         63.0
     x16th.week                     NaN         84.0
     x17th.week                     NaN         85.0
     x18th.week                     NaN         87.0
     x19th.week                     NaN         95.0
     x1st.week                     80.0         87.0
     x20th.week                     NaN        100.0
     x21st.week                     NaN          NaN
     x22nd.week                     NaN          NaN
     x23rd.week                     NaN          NaN
     x24th.week                     NaN          NaN
     x25th.week                     NaN          NaN
     x26th.week                     NaN          NaN
     x27th.week                     NaN          NaN
     x28th.week                     NaN          NaN
     x29th.week                     NaN          NaN
     x2nd.week                     78.0         73.0
     x30th.week                     NaN          NaN
     x31st.week                     NaN          NaN
     x32nd.week                     NaN          NaN
     x33rd.week                     NaN          NaN
     x34th.week                     NaN          NaN
     x35th.week                     NaN          NaN
     x36th.week                     NaN          NaN
     x37th.week                     NaN          NaN
...                                 ...          ...
     x52nd.week                     NaN          NaN
     x53rd.week                     NaN          NaN
     x54th.week                     NaN          NaN
     x55th.week                     NaN          NaN
     x56th.week                     NaN          NaN
     x57th.week                     NaN          NaN
     x58th.week                     NaN          NaN
     x59th.week                     NaN          NaN
     x5th.week                     92.0         58.0
     x60th.week                     NaN          NaN
     x61st.week                     NaN          NaN
     x62nd.week                     NaN          NaN
     x63rd.week                     NaN          NaN
     x64th.week                     NaN          NaN
     x65th.week                     NaN          NaN
     x66th.week                     NaN          NaN
     x67th.week                     NaN          NaN
     x68th.week                     NaN          NaN
     x69th.week                     NaN          NaN
     x6th.week                      NaN         57.0
     x70th.week                     NaN          NaN
     x71st.week                     NaN          NaN
     x72nd.week                     NaN          NaN
     x73rd.week                     NaN          NaN
     x74th.week                     NaN          NaN
     x75th.week                     NaN          NaN
     x76th.week                     NaN          NaN
     x7th.week                      NaN         51.0
     x8th.week                      NaN         47.0
     x9th.week                      NaN         44.0

genre                                                                         \
artist.inverted               Brock, Chad                      Brooks & Dunn
track           A Country Boy Can Survive  Yes! You'll Always Be Loved By Me
year week
2000 x10th.week                       NaN  31.0                         68.0
     x11th.week                       NaN  28.0                         62.0
     x12th.week                       NaN  27.0                         56.0
     x13th.week                       NaN  22.0                         56.0
     x14th.week                       NaN  27.0                         55.0
     x15th.week                       NaN  31.0                         62.0
     x16th.week                       NaN  39.0                         71.0
     x17th.week                       NaN  45.0                         86.0
     x18th.week                       NaN  50.0                        100.0
     x19th.week                       NaN  53.0                         98.0
     x1st.week                       93.0  90.0                         95.0
     x20th.week                       NaN  59.0                          NaN
     x21st.week                       NaN   NaN                          NaN
     x22nd.week                       NaN   NaN                          NaN
     x23rd.week                       NaN   NaN                          NaN
     x24th.week                       NaN   NaN                          NaN
     x25th.week                       NaN   NaN                          NaN
     x26th.week                       NaN   NaN                          NaN
     x27th.week                       NaN   NaN                          NaN
     x28th.week                       NaN   NaN                          NaN
     x29th.week                       NaN   NaN                          NaN
     x2nd.week                       75.0  77.0                         85.0
     x30th.week                       NaN   NaN                          NaN
     x31st.week                       NaN   NaN                          NaN
     x32nd.week                       NaN   NaN                          NaN
     x33rd.week                       NaN   NaN                          NaN
     x34th.week                       NaN   NaN                          NaN
     x35th.week                       NaN   NaN                          NaN
     x36th.week                       NaN   NaN                          NaN
     x37th.week                       NaN   NaN                          NaN
...                                   ...   ...                          ...
     x52nd.week                       NaN   NaN                          NaN
     x53rd.week                       NaN   NaN                          NaN
     x54th.week                       NaN   NaN                          NaN
     x55th.week                       NaN   NaN                          NaN
     x56th.week                       NaN   NaN                          NaN
     x57th.week                       NaN   NaN                          NaN
     x58th.week                       NaN   NaN                          NaN
     x59th.week                       NaN   NaN                          NaN
     x5th.week                        NaN  59.0                         83.0
     x60th.week                       NaN   NaN                          NaN
     x61st.week                       NaN   NaN                          NaN
     x62nd.week                       NaN   NaN                          NaN
     x63rd.week                       NaN   NaN                          NaN
     x64th.week                       NaN   NaN                          NaN
     x65th.week                       NaN   NaN                          NaN
     x66th.week                       NaN   NaN                          NaN
     x67th.week                       NaN   NaN                          NaN
     x68th.week                       NaN   NaN                          NaN
     x69th.week                       NaN   NaN                          NaN
     x6th.week                        NaN  47.0                         83.0
     x70th.week                       NaN   NaN                          NaN
     x71st.week                       NaN   NaN                          NaN
     x72nd.week                       NaN   NaN                          NaN
     x73rd.week                       NaN   NaN                          NaN
     x74th.week                       NaN   NaN                          NaN
     x75th.week                       NaN   NaN                          NaN
     x76th.week                       NaN   NaN                          NaN
     x7th.week                        NaN  39.0                         82.0
     x8th.week                        NaN  33.0                         74.0
     x9th.week                        NaN  32.0                         74.0

genre                                                       \
artist.inverted        Brooks, Garth           Byrd, Tracy
track           Do What You Gotta Do Put Your Hand In Mine
year week
2000 x10th.week                  NaN                   NaN
     x11th.week                  NaN                   NaN
     x12th.week                  NaN                   NaN
     x13th.week                  NaN                   NaN
     x14th.week                  NaN                   NaN
     x15th.week                  NaN                   NaN
     x16th.week                  NaN                   NaN
     x17th.week                  NaN                   NaN
     x18th.week                  NaN                   NaN
     x19th.week                  NaN                   NaN
     x1st.week                  86.0                  81.0
     x20th.week                  NaN                   NaN
     x21st.week                  NaN                   NaN
     x22nd.week                  NaN                   NaN
     x23rd.week                  NaN                   NaN
     x24th.week                  NaN                   NaN
     x25th.week                  NaN                   NaN
     x26th.week                  NaN                   NaN
     x27th.week                  NaN                   NaN
     x28th.week                  NaN                   NaN
     x29th.week                  NaN                   NaN
     x2nd.week                  81.0                  77.0
     x30th.week                  NaN                   NaN
     x31st.week                  NaN                   NaN
     x32nd.week                  NaN                   NaN
     x33rd.week                  NaN                   NaN
     x34th.week                  NaN                   NaN
     x35th.week                  NaN                   NaN
     x36th.week                  NaN                   NaN
     x37th.week                  NaN                   NaN
...                              ...                   ...
     x52nd.week                  NaN                   NaN
     x53rd.week                  NaN                   NaN
     x54th.week                  NaN                   NaN
     x55th.week                  NaN                   NaN
     x56th.week                  NaN                   NaN
     x57th.week                  NaN                   NaN
     x58th.week                  NaN                   NaN
     x59th.week                  NaN                   NaN
     x5th.week                  69.0                  86.0
     x60th.week                  NaN                   NaN
     x61st.week                  NaN                   NaN
     x62nd.week                  NaN                   NaN
     x63rd.week                  NaN                   NaN
     x64th.week                  NaN                   NaN
     x65th.week                  NaN                   NaN
     x66th.week                  NaN                   NaN
     x67th.week                  NaN                   NaN
     x68th.week                  NaN                   NaN
     x69th.week                  NaN                   NaN
     x6th.week                  77.0                  88.0
     x70th.week                  NaN                   NaN
     x71st.week                  NaN                   NaN
     x72nd.week                  NaN                   NaN
     x73rd.week                  NaN                   NaN
     x74th.week                  NaN                   NaN
     x75th.week                  NaN                   NaN
     x76th.week                  NaN                   NaN
     x7th.week                   NaN                  92.0
     x8th.week                   NaN                  99.0
     x9th.week                   NaN                   NaN

genre                                        ...                Rock  \
artist.inverted           Cagle, Chris       ...               Usher
track           My Love Goes On And On       ...       Pop Ya Collar
year week                                    ...
2000 x10th.week                   83.0       ...                 NaN
     x11th.week                   91.0       ...                 NaN
     x12th.week                    NaN       ...                 NaN
     x13th.week                    NaN       ...                 NaN
     x14th.week                    NaN       ...                 NaN
     x15th.week                    NaN       ...                 NaN
     x16th.week                    NaN       ...                 NaN
     x17th.week                    NaN       ...                 NaN
     x18th.week                    NaN       ...                 NaN
     x19th.week                    NaN       ...                 NaN
     x1st.week                    99.0       ...                68.0
     x20th.week                    NaN       ...                 NaN
     x21st.week                    NaN       ...                 NaN
     x22nd.week                    NaN       ...                 NaN
     x23rd.week                    NaN       ...                 NaN
     x24th.week                    NaN       ...                 NaN
     x25th.week                    NaN       ...                 NaN
     x26th.week                    NaN       ...                 NaN
     x27th.week                    NaN       ...                 NaN
     x28th.week                    NaN       ...                 NaN
     x29th.week                    NaN       ...                 NaN
     x2nd.week                    94.0       ...                64.0
     x30th.week                    NaN       ...                 NaN
     x31st.week                    NaN       ...                 NaN
     x32nd.week                    NaN       ...                 NaN
     x33rd.week                    NaN       ...                 NaN
     x34th.week                    NaN       ...                 NaN
     x35th.week                    NaN       ...                 NaN
     x36th.week                    NaN       ...                 NaN
     x37th.week                    NaN       ...                 NaN
...                                ...       ...                 ...
     x52nd.week                    NaN       ...                 NaN
     x53rd.week                    NaN       ...                 NaN
     x54th.week                    NaN       ...                 NaN
     x55th.week                    NaN       ...                 NaN
     x56th.week                    NaN       ...                 NaN
     x57th.week                    NaN       ...                 NaN
     x58th.week                    NaN       ...                 NaN
     x59th.week                    NaN       ...                 NaN
     x5th.week                    84.0       ...                62.0
     x60th.week                    NaN       ...                 NaN
     x61st.week                    NaN       ...                 NaN
     x62nd.week                    NaN       ...                 NaN
     x63rd.week                    NaN       ...                 NaN
     x64th.week                    NaN       ...                 NaN